apiVersion: v1
kind: Service
metadata:
  name: echoserver-svc
spec:
  selector:
    app: echo-server
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80 # the port that this service should serve on
    targetPort: 8888 
