apiVersion: v1
kind: Service
metadata:
  name: flask-app-svc
  labels:
    run: flask-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    run: flask-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-dpl
spec:
  selector:
    matchLabels:
      run: flask-app
  replicas: 3
  template:
    metadata:
      labels:
        run: flask-app
    spec:
      containers:
      - name: flask-app
        image: raddaoui/flask-app:1f3e4101df8fc42b7bb5b81dcbf87c9af4f1b883
        ports:
        - containerPort: 5000
